.catalog:
  version: dev

version: '2'
services:
  lb-for-load:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - path: ''
        protocol: http
        service: global-load
        source_port: 80
        target_port: 80
      - path: ''
        protocol: http
        service: scaling-load
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  global-load:
    start_on_create: true
  scaling-load:
    scale: 1
    start_on_create: true
  curler:
    start_on_create: true
